# Specify version format
version: "1.4.0.{build}"

# Image to use
image: Visual Studio 2019

# Branches to build
branches:
  only: 
    - master

# Including commits with 'build' comment
only_commits:
  message: build

# Build matrix
environment:
  matrix:
    - type: VisualStudio
      build: call vs.bat
      command: cmd /C

# Allow to fail on first error in matrix
matrix:
  fast_finish: true

# Scripts that run after cloning repository
install:
  # Chocolatey
  - choco upgrade chocolatey
  # CMake
  - '%command% "cmake --version"'

# Build scripts
build_script:
  - cd build
  - '%build%'

# Test scripts
test: off
