# .NET Core
language: csharp
mono: none
dotnet: 3.1.300
solution: NetCoreServer.sln

# OS environment
dist: focal

# Build matrix (OS, compiler)
matrix:
  include:
    - name: "Linux"
      os: linux
    - name: "MacOS"
      os: osx
      osx_image: xcode12u

# Build scripts
script:
  - dotnet restore
  - dotnet build
  - dotnet test
