# .NET Core
language: csharp
mono: none
dotnet: 3.0.100-preview8-013656
solution: NetCoreServer.sln

# OS environment
dist: xenial

# Build matrix (OS, compiler)
matrix:
  include:
    - name: "Linux"
      os: linux
    - name: "MacOS"
      os: osx
      osx_image: xcode11

# Build scripts
script:
  - dotnet restore
  - dotnet build
  - dotnet test
