name: Windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2

      - name: "Setup dotnet"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: "Build"
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet test
